(function(){var w=window.I18N;var d=w&&w["zh-cn"];if(!d)return;Object.assign(d,{hero:{back:"返回 Blog",category:"设计 · API",tools:{reportIssue:"反馈页面问题",copyLink:"复制链接"},author:"by rhosocial 团队",title:"流式 API：ActiveRecord 与 ActiveQuery",sub:"让代码读起来像英语——流式 API 的设计哲学与实践。"},body:[{tag:"lead",html:"好的 API 应当像一门自然语言——读起来流畅，写起来自然。rhosocial ActiveRecord 的流式 API（Fluent API）正是基于这一理念设计的。<code>user.save()</code> 读作\"用户保存\"，<code>User.query().where(...).order_by(...).all()</code> 读作\"用户查询·条件·排序·全部\"。这篇文章将介绍 rhosocial-activerecord 流式 API 的设计哲学和关键实践。"},
{tag:"h2",html:"ActiveRecord.save() 与 .delete()：模型即数据源"},
{tag:"p",html:"rhosocial-activerecord 最核心的 API 是模型实例上的 <code>save()</code> 和 <code>delete()</code> 方法。CRUD 操作封装为模型对象上的方法调用，让代码表达意图而非实现细节："},
{tag:"code",lang:"python",text:"# 创建\nuser = User(name=\"Alice\", email=\"alice@example.com\")\nuser.save()\n\n# 更新\nuser.name = \"Bob\"\nuser.save()\n\n# 删除\nuser = User.find_one(1)\nuser.delete()"},
{tag:"p",html:"<code>save()</code> 会根据 <code>is_new_record</code> 自动判断 INSERT 还是 UPDATE——新建实例执行 INSERT，已持久化实例执行 UPDATE。UPDATE 时<strong>只包含脏字段</strong>（<code>dirty_fields</code>），即从上次持久化以来被修改过的字段，不会无谓地 SET 所有列。"},
{tag:"p",html:"某些场景需要<strong>始终更新特定字段</strong>，例如 <code>TimestampMixin</code> 会在每次 <code>BEFORE_UPDATE</code> 事件中将 <code>updated_at</code> 设为当前时间——不论该字段是否被标记为脏。"},
{tag:"p",html:"<code>delete()</code> 从数据库中移除记录。两者都返回受影响的行数（<code>int</code>）。"},
{tag:"p",html:"查找记录使用类方法 <code>find_one()</code>、<code>find_all()</code>、<code>find_one_or_fail()</code>，或通过 ActiveQuery 构建复杂查询。"},
{tag:"h2",html:"ActiveQuery：构建查询"},
{tag:"p",html:"ActiveQuery 是 rhosocial-activerecord 的流式查询构建器。每个方法返回 <code>self</code>，支持链式调用。查询在终端方法（如 <code>.all()</code>、<code>.one()</code>）时才实际执行——即延迟执行（Lazy Evaluation）："},
{tag:"code",lang:"python",text:"users = User.query()\\\n    .where(User.c.age >= 18)\\\n    .where(User.c.status == \"active\")\\\n    .order_by((User.c.name, \"ASC\"))\\\n    .limit(10)\\\n    .all()"},
{tag:"p",html:"延迟执行有两个好处："},
{tag:"ul",items:["开发者可以按需组合查询条件，而不是一次性传递所有参数","ActiveQuery 在执行前可以对整个查询进行优化，比如合并条件、去除冗余子句","调用 <code>.to_sql()</code> 可以随时查看生成的 SQL 和参数，无需实际执行"]},
{tag:"h2",html:"终端方法"},
{tag:"p",html:"链式调用的终点是终端方法（Terminal Method），它们执行查询并返回结果："},
{tag:"ul",items:["<strong><code>.all()</code></strong>——返回所有匹配记录的列表（<code>List[Model]</code>），若无结果则为空列表","<strong><code>.one()</code></strong>——返回唯一一条匹配记录（<code>Optional[Model]</code>），多条记录时抛出异常","<strong><code>.count()</code></strong>——返回匹配记录的数量（<code>int</code>），生成 <code>SELECT COUNT(*)</code>","<strong><code>.exists()</code></strong>——返回是否存在匹配记录（<code>bool</code>），短路优化","<strong><code>.to_sql()</code></strong>——返回生成的 SQL 字符串和参数元组（<code>(str, tuple)</code>），不执行"]},
{tag:"h2",html:"查询方法"},
{tag:"p",html:"构建查询的中间方法（Intermediate Method）可以任意组合："},
{tag:"ul",items:["<strong><code>.where(predicate)</code></strong>——添加过滤条件，可多次调用，多条件之间为 AND 关系","<strong><code>.select(*columns)</code></strong>——指定返回列，默认 <code>SELECT *</code>","<strong><code>.order_by(*clauses)</code></strong>——指定排序字段，传入 <code>(column, 'ASC')</code> / <code>(column, 'DESC')</code> 元组","<strong><code>.limit(n)</code></strong>——限制返回行数","<strong><code>.offset(n)</code></strong>——分页偏移","<strong><code>.join(model, on=condition, alias=name)</code></strong>——多表连接","<strong><code>.group_by(*columns)</code></strong>——分组聚合","<strong><code>.having(condition)</code></strong>——分组过滤"]},
{tag:"h2",html:"表达式驱动——.c 字段代理"},
{tag:"p",html:"查询条件通过 <code>User.c.field</code> 表达式构造，而非关键字参数。这是 rhosocial-activerecord 区别于 Django ORM 的设计选择："},
{tag:"ul",items:["<strong>.where(User.c.age >= 18)</strong>——通过 Python 运算符重载构造查询条件","<strong>.where(User.c.name.like(\"%Alice%\"))</strong>——字符串方法","<strong>.where(User.c.id.in_([1, 2, 3]))</strong>——集合判断","<strong>.where(User.c.deleted_at.is_null())</strong>——空值判断"]},
{tag:"p",html:"每个 <code>User.c.field</code> 都会生成一个 <code>Column</code> 表达式节点，支持完整的 Python 比较运算符和链式表达式方法。表达式节点可以调用 <code>.to_sql()</code> 随时查看 SQL。"},
{tag:"h2",html:"链式调用的组合性"},
{tag:"p",html:"ActiveQuery 的链式调用支持条件的自由组合。开发者可以基于条件分支构建不同的查询变体："},
{tag:"code",lang:"python",text:"def search_users(name=None, min_age=None, active_only=False):\n    q = User.query()\n    if name:\n        q = q.where(User.c.name.like(f\"%{name}%\"))\n    if min_age:\n        q = q.where(User.c.age >= min_age)\n    if active_only:\n        q = q.where(User.c.status == \"active\")\n    return q.order_by((User.c.name, \"ASC\")).all()"},
{tag:"p",html:"每个 <code>.where()</code> 返回新的 ActiveQuery 实例，条件不是突变的而是累积的——这让查询构建函数可以安全地分支配逻辑，不会意外修改原始查询。"},
{tag:"h2",html:"与 Pydantic 的集成"},
{tag:"p",html:"<code>save()</code> 在执行数据库操作前会触发一次完整的 Pydantic 字段验证。即使绕过了类型注解直接设置字段值，rhosocial-activerecord 也能在持久化前捕获数据问题。"},
{tag:"p",html:"同时支持 <code>save(validate=False)</code> 跳过验证，适用于性能敏感或已预先验证的场景。"},
{tag:"h2",html:"总结"},
{tag:"p",html:"rhosocial-activerecord 的流式 API 设计遵循三个原则："},
{tag:"ul",items:["<strong>可读性优先</strong>——<code>user.save()</code> / <code>user.delete()</code> 读作自然语言，非符号序列","<strong>延迟执行</strong>——查询构建和执行分离，<code>.to_sql()</code> 透明查看 SQL","<strong>可组合性</strong>——查询条件是自由组合的积木，每个 <code>.where()</code> 返回新实例"]},
{tag:"hr"},
{tag:"next",html:"下一篇：关系映射——belongs_to / has_many 的声明式定义与加载策略。"}]})})();